### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by Ryo04k** [Ryo04k/FragranceMe#30]
issueを作成いたしました。
レビューをお願いいたします。

■Webアプリの概要
フレグランスショップを簡単に検索できるサービスです。
- 具体的な機能：
  - 現在地、地域、住所からショップを検索
  - 店舗詳細の確認やユーザー間で口コミを投稿
  - Ai を活用し、ユーザーの気分やシーンに合わせた商品や香り、ブランドを提案

■1週間辺りの開発に向けられる時間
- 1週間あたり：約20〜25時間

■ProjectsのURL
[FragranceMe開発プロジェクト](https://github.com/users/Ryo04k/projects/1/views/1)

■MVPリリースまで
- [ ] TOP ページ
- [ ] ユーザー登録、ログイン
- [ ] ショップ検索（DB 保存）
  - [ ] フリーワード
  - [ ] 地域
- [ ] 店舗の詳細
  - [ ] 店名
  - [ ]  郵便番号
  - [ ]  住所
  - [ ]  営業時間
  - [ ]  電話番号
  - [ ]  公式サイト
  - [ ]  店舗画像
  - [ ]  GoogleMap

■MVP後

- [ ] AIによるレコメンド機能
- [ ] Google認証
- [ ] Xシェア（OGP）
- [ ] 現在地から検索（周辺店舗をマップ表示）
- [ ] 店舗レビュー（投稿・編集・削除機能・画像投稿）
- [ ] 店舗お気に入り登録
- [ ] マイページ
- [ ] オートコンプリート機能
- [ ] 店舗エリア拡大

■MVPレビュー依頼予定日
予定日：2024年 12月 9日

**Comment by kenchasonakai** [comment]
LGTMです！
